name: Deploy Creatoke Api

on:
  push:
    branches:
      - main  # DÃ©clenchement sur la branche principale

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Cloner le dÃ©pÃ´t
      uses: actions/checkout@v2

    - name: âš¡ Installer Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: ğŸ“¦ Installer les dÃ©pendances
      run: npm install

    - name: ğŸ—ï¸ Running app...
      run: npm start

    - name: ğŸš€ DÃ©ployer sur le serveur via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "creatoke-api/*"
        target: "/var/www/html/creatoke-api"